
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-UCSBOrgPlaceholder","number":88,"title":"azhu - UCSB Organization placeholder pages","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/88"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-MenuItemReview-frontend3","number":87,"title":"Copy placeholders for menu item review","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/87"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-UCSBOrgTable","number":86,"title":"azhu - UCSB Organization table","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/86"},{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-HelpRequest-FormComponent-3","number":85,"title":"Sasha - Created Form Components for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/85"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-RecommendationRequest-placeholders","number":83,"title":"BC - Added placeholder for recommendation requests service","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/83"}]
