
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-4
pull_requests: [{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-HelpRequest-Fixture-2","number":74,"title":"AN - Created fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/74"},{"author":{"id":"MDQ6VXNlcjc2NDUzODIw","is_bot":false,"login":"EricM5","name":"Eric Marzouk"},"headRefName":"Eric-backend2","number":73,"title":"em - added fixtures file for Menu Item","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/73"}]
