
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-RecommendationRequest-edit","number":109,"title":"BC - Added edit page for recommendation request ","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/109"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-RecommendationRequest-index","number":108,"title":"BC - Added Index for Recommendation Request Service","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/108"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-RecommendationRequest-pages","number":107,"title":"BC - Added Create Page for the Recommendation Request Service","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/107"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"BC-RecommendationRequest-placeholders","number":106,"title":"BC - Added Placeholders for RecRequest Service","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/106"},{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-HelpRequest-Pages-6","number":105,"title":"Sasha - \"Create\" page for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/105"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Articles-editpage","number":104,"title":"azhou - Articles edit page, tests, and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/104"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-UCSBOrgCreate","number":94,"title":"azhu - UCSB Organizations Create Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/94"},{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-MenuItemReview-frontend4","number":93,"title":"create page for menu item review","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/93"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-UCSBOrgPlaceholder","number":88,"title":"azhu - UCSB Organization placeholder pages","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/88"}]
