
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-4
pull_requests: [{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-HelpRequest-Edit-8","number":111,"title":"Sasha - Create Edit for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/111"},{"author":{"id":"U_kgDOCLmq2Q","is_bot":false,"login":"anisavic","name":"Sasha"},"headRefName":"Sasha-HelpRequest-Index-7","number":110,"title":"Sasha - Create Index Page for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/110"}]
