
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-MenuItemReview-backend2","number":67,"title":"added fixtures for menu item review","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/67"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Articles-fixture","number":66,"title":"azhou - Create fixtures for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/66"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Azhu-UCSBOrgFixtures","number":63,"title":"azhu - Adding Fixtures for UCSB organizations","url":"https://github.com/ucsb-cs156-f23/team03-f23-7pm-4/pull/63"}]
